version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7
    environment:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
        command: |
          sudo pip install pipenv
          pipenv lock --pre
          pipenv run python -m unittest tests.test_generator